_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: a6d103d1-7c35-4eae-a5c5-e5633b9cdc14
name: 'Local Employee Management Portal'
mail: aftabansari1024@gmail.com
slogan: ''
page:
  403: /node/2
  404: /node/1
  front: /homepage
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
